module.exports = {
  ...require('./dashboard'),
  ...require('./profile'),
  ...require('./body'),
  ...require('./food'),
  ...require('./workouts'),
  ...require('./study'),
  ...require('./plans'),
  ...require('./plan-timers'),
  ...require('./daily-reviews'),
  ...require('./privacy'),
  ...require('./friends'),
  ...require('./groups'),
  ...require('./notes'),
  ...require('./notifications'),
  ...require('./feedback'),
  ...require('./reports'),
  ...require('./system')
}
