module.exports = Object.freeze({
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_NOT_INITIALIZED: 'DATABASE_NOT_INITIALIZED',
  WEIGHT_UPDATE_REQUIRED: 'WEIGHT_UPDATE_REQUIRED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_DISABLED: 'PLAN_DISABLED',
  PLAN_NOT_DUE: 'PLAN_NOT_DUE',
  PLAN_WEEKLY_TARGET_REACHED: 'PLAN_WEEKLY_TARGET_REACHED',
  FRIEND_PERMISSION_DENIED: 'FRIEND_PERMISSION_DENIED',
  GROUP_PERMISSION_DENIED: 'GROUP_PERMISSION_DENIED',
  GROUP_OWNER_CANNOT_LEAVE: 'GROUP_OWNER_CANNOT_LEAVE',
  FOOD_NOT_FOUND: 'FOOD_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_ATTACHMENT_INVALID: 'NOTE_ATTACHMENT_INVALID'
})
